version: "3"

services:
  db:
    container_name: ${NAME}-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: unless-stopped
    expose:
      - '3306'

  nginx:
    container_name: ${NAME}-nginx
    image: nginx:alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./:/var/www/
    expose:
      - '80'
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${SITE_DOMAIN}"
    links:
        - wordpress

  wordpress:
    container_name: ${NAME}-wordpress
    build:
      context: ./config/docker
      dockerfile: wordpress.Dockerfile
    depends_on:
      - db
    expose:
      - '9000'
    volumes:
      - ./:/var/www/
      - ./config/php/php.conf:/usr/local/etc/php/conf.d/php.ini
    restart: unless-stopped
    links:
      - db
    environment:
      PHP_AUTOCONF: /usr/bin/autoconf
      
  mailhog:
    container_name: ${NAME}-mailhog
    image: mailhog/mailhog:latest
    depends_on:
      - wordpress
    expose:
      - '8025'
      - '1025'
    restart: unless-stopped
    links:
      - wordpress
      - toolbox
    environment:
      VIRTUAL_HOST: "${MAIL_DOMAIN}"
      VIRTUAL_PORT: 8025

  toolbox:
    container_name: ${NAME}-toolbox
    image: wordpress:cli
    command: tail -f /dev/null
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - wordpress
      - db

networks:
  default:
    external:
      name: nginx-proxy

